### PR TITLE
Modify calls to hy_sack_create for hawkey 0.6.3.

### PR DESCRIPTION
**Pull request by rwmjones**
Signed-off-by: Richard W.M. Jones rjones@redhat.com

### CODE REVIEW

**Comment by rwmjones** [comment]
I know that hawkey is apparently "dead" and libdnf is the new thing, but this at least fixes tdnf so it build with the current dependencies.

**Comment by ppadmavilasom** [comment]
Thanks for the PR. Could you please send this to the dev branch?

**Comment by Conan-Kudo** [comment]
@ppadmavilasom Why do you guys still have a CLA for tdnf? It makes no sense, especially since the copyleft provisions of the code itself are a strong enough guarantee...

**Comment by Conan-Kudo** [comment]
This can be closed now, as this PR is not relevant with the 2.0.0+ code.

**Pull request closed without merging**
