### PR TITLE
Add installroot command line option.

### PR DESCRIPTION
**Pull request by xiaolin-vmware**

### CODE REVIEW

**Comment by ppadmavilasom** [comment]
This supports installs. Can we also add the rootdir (if set) when we create a sack (hy_sack_create)
Also, please send the pull request to dev

**Comment by toliaqat** [comment]
It does not seems to be creating a chroot to install the rpms in installroot. Can we check if yum is doing the same thing. I thought creating a chroot to isolate the installation was part of requirement for this task. Not having a chroot the postinstall scripts of rpm could harm the actual root???

**Comment by ppadmavilasom** [comment]
@toliaqat assumes chroot exists and rpmdb is initialized. This is the same with yum
<code>rpm --root /myroot --initdb</code>

**Comment by toliaqat** [comment]
rpm will fill out the new chroot with db, but a rpm package during installation can execute some post-install scripts that could be pointing to / instead of installdir.

**Comment by ppadmavilasom** [comment]
@toliaqat: do we have an instance that this fails? rpmtsSetRootDir is called with the new root.

**Pull request merged**
