### PR TITLE
Fix issue: https://github.com/vmware/tdnf/issues/95

### PR DESCRIPTION
**Pull request by ppadmavilasom**

### CODE REVIEW

**Review by tapakund — APPROVED** [review]
LGTM

**Review by tapakund — COMMENTED** [review]
Shall we set dwError explicitly to :
dwError = ENOENT

But i think setting to errno is better.

**Comment by keerthanakalyan** [comment]
@ppadmavilasom : pCacheFile can be NULL, repo_add_rpmdb_reffp 
 handles both NULL and not NULL values https://github.com/openSUSE/libsolv/blob/a7cbcc3a5cfae21afc6bd95e3907da7b276c17bd/ext/repo_rpmdb.c#L1846. I hope this change is not required.

**Comment by ppadmavilasom** [comment]
> @ppadmavilasom : pCacheFile can be NULL, repo_add_rpmdb_reffp
> handles both NULL and not NULL values https://github.com/openSUSE/libsolv/blob/a7cbcc3a5cfae21afc6bd95e3907da7b276c17bd/ext/repo_rpmdb.c#L1846. I hope this change is not required.

@keerthanakalyan i added a check so we wont error out when cache file not present. if cachefile is present and we still error, we should handle.

**Pull request merged**
