### PR TITLE
Add helper script to build tdnf using llvm

### PR DESCRIPTION
**Pull request by sshedi**
I was just playing around with this and it took a while to get it working. So added a helper script to do it.

Also, llvm build showed some good warnings, fixed them all.

### CODE REVIEW

**Comment by oliverkurth** [comment]
This is completely optional, correct? Is there any advantage in using `llvm`?

**Comment by oliverkurth** [comment]
Also, I think it would be good to run all tests when built this way.

In any case, the warning fixes are good.

**Comment by sshedi** [comment]
> This is completely optional, correct? Is there any advantage in using `llvm`?

Completely optional. Just dog fooding. I don't even want it to add to our workflow, llvm, clang together add ~2GB download size. It makes test runs really slow.

**Comment by sshedi** [comment]
> any advantage in using llvm?

Warnings, maybe sometimes build might not work. It would be nice to keep our code compatible with gcc, clang both.

**Pull request merged**
